SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes 
GROUP BY ESTADO HAVING LIMITE_TOTAL > 300000;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS MAXIMO_PRECIO, MIN(PRECIO_DE_LISTA) AS MINIMO_PRECIO,
SUM(PRECIO_DE_LISTA) AS SUMA_TOTAL FROM tabla_de_productos GROUP BY ENVASE;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS MAXIMO_PRECIO, MIN(PRECIO_DE_LISTA) AS MINIMO_PRECIO,
SUM(PRECIO_DE_LISTA) AS SUMA_TOTAL FROM tabla_de_productos GROUP BY ENVASE HAVING SUMA_TOTAL > 80;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS MAXIMO_PRECIO, MIN(PRECIO_DE_LISTA) AS MINIMO_PRECIO,
SUM(PRECIO_DE_LISTA) AS SUMA_TOTAL FROM tabla_de_productos GROUP BY ENVASE HAVING SUMA_TOTAL > 80
AND MAXIMO_PRECIO >= 15;