SELECT DISTINCT BARRIO FROM tabla_de_clientes;
SELECT DISTINCT BARRIO FROM tabla_de_vendedores;

SELECT DISTINCT BARRIO FROM tabla_de_clientes
UNION	
SELECT DISTINCT BARRIO FROM tabla_de_vendedores;

SELECT DISTINCT BARRIO FROM tabla_de_clientes
UNION ALL
SELECT DISTINCT BARRIO FROM tabla_de_vendedores;

SELECT DISTINCT BARRIO, NOMBRE, 'CLIENTE' AS TIPO FROM tabla_de_clientes
UNION	
SELECT DISTINCT BARRIO, NOMBRE, 'VENDEDOR' AS TIPO FROM tabla_de_vendedores;

SELECT TC.NOMBRE, TC.CIUDAD, TC.BARRIO, TV.NOMBRE, VACACIONES  
FROM tabla_de_clientes TC
LEFT JOIN tabla_de_vendedores TV
ON TC.BARRIO = TV.BARRIO
UNION
SELECT TC.NOMBRE, TC.CIUDAD, TC.BARRIO, TV.NOMBRE, VACACIONES  
FROM tabla_de_clientes TC
RIGHT JOIN tabla_de_vendedores TV
ON TC.BARRIO = TV.BARRIO;