SELECT * FROM tabla_de_productos;

SELECT NOMBRE_DEL_PRODUCTO, PRECIO_DE_LISTA, 
CASE
	WHEN PRECIO_DE_LISTA >= 12 THEN 'Costoso'
    WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'Absequible!'
    ELSE 'Barato'
END AS PRECIO
FROM tabla_de_productos ORDER BY PRECIO;

SELECT ENVASE, SABOR, TAMANO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO,
CASE
	WHEN PRECIO_DE_LISTA >= 12 THEN 'Costoso'
    WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'Absequible'
    ELSE 'Barato'
END AS PRECIO
FROM tabla_de_productos 
WHERE TAMANO = '700 ml'
GROUP BY ENVASE, SABOR, TAMANO,
CASE
	WHEN PRECIO_DE_LISTA >= 12 THEN 'Costoso'
    WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'Absequible'
    ELSE 'Barato'
END
ORDER BY PRECIO_MINIMO;

